---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/osodevops/confluent-gitops-demo.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: confluent-infra
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomize/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: confluent
      namespace: confluent
  validation: client
---
# SANDBOX ENVIRONMENT
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sandbox
  namespace: flux-system
spec:
  dependsOn:
    - name: confluent-infra
  interval: 1m
  path: ./kustomize/environments/sandbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# PRODUCTION ENVIRONMENT
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: production
  namespace: flux-system
spec:
  dependsOn:
    - name: confluent-infra
  interval: 1m
  path: ./kustomize/environments/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
#TERRAFORM CONTROLLER
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: terraform-controller
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomize/tf-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: tf-controller
      namespace: flux-system
  validation: client