apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - namespace.yaml
  - ../../base
  - ../../base/confluent/schmea-registry
  - ../../base/confluent/connect
  - ../../base/confluent/control-centre