apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sandbox
resources:
  - namespace.yaml
  - ../../base
  - ../../base/confluent/schmea-registry
patchesStrategicMerge:
  - zookeeper.yaml
  - kafka.yaml